[project]
name = "api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.9"
dependencies = [
    "fastapi[standard]>=0.115.11",
    "langchain>=0.3.21",
    "openai>=1.68.2",
]

[dependency-groups]
dev = [
    "ruff>=0.11.2",
]
